#!/usr/bin/env bash
#manage my process

PID_FILE="/var/run/my_process.pid"
PROCESS_NAME="manage_my_process"

start_process() {
  if [ -f "$PID_FILE" ]; then
        echo "$PROCESS_NAME is already running (PID in $PID_FILE). Start will create another instance."
  fi
  $PROCESS_NAME &
  PID=$!
  echo "$PID" > "$PID_FILE"
  echo "$PROCESS_NAME started (PID: $PID)"
}

stop_process() {
  if [ -f "$PID_FILE" ]; then
    PID=$(cat "$PID_FILE")
    kill "$PID" 2>/dev/null  # Suppress "no such process" error if already killed
    rm "$PID_FILE"
    echo "$PROCESS_NAME stopped"
  else
    echo "$PROCESS_NAME is not running."
  fi
}

restart_process() {
  stop_process
  start_process
  echo "$PROCESS_NAME restarted"
}

case "$1" in
  start)
    start_process
    ;;
  stop)
    stop_process
    ;;
  restart)
    restart_process
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
